# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: medconnect.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10medconnect.proto\x12\nmedconnect\"\x14\n\x12HealthCheckRequest\"6\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"X\n\x13\x43onversationRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\r\n\x05\x61udio\x18\x02 \x01(\t\x12\x0f\n\x07premium\x18\x03 \x01(\x08\x12\x10\n\x08language\x18\x04 \x01(\t\"b\n\x14\x43onversationResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\r\n\x05\x61udio\x18\x02 \x01(\t\x12\x11\n\tdoctor_id\x18\x03 \x01(\t\x12\x17\n\x0fmedical_summary\x18\x04 \x01(\t\"\x0e\n\x0cResetRequest\"\x1f\n\rResetResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"U\n\x10TranslateRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x17\n\x0fsource_language\x18\x02 \x01(\t\x12\x17\n\x0ftarget_language\x18\x03 \x01(\t\"$\n\x11TranslateResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xbe\x02\n\x11MedConnectService\x12N\n\x0bHealthCheck\x12\x1e.medconnect.HealthCheckRequest\x1a\x1f.medconnect.HealthCheckResponse\x12Q\n\x0c\x43onversation\x12\x1f.medconnect.ConversationRequest\x1a .medconnect.ConversationResponse\x12<\n\x05Reset\x12\x18.medconnect.ResetRequest\x1a\x19.medconnect.ResetResponse\x12H\n\tTranslate\x12\x1c.medconnect.TranslateRequest\x1a\x1d.medconnect.TranslateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'medconnect_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_HEALTHCHECKREQUEST']._serialized_start=32
  _globals['_HEALTHCHECKREQUEST']._serialized_end=52
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=54
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=108
  _globals['_CONVERSATIONREQUEST']._serialized_start=110
  _globals['_CONVERSATIONREQUEST']._serialized_end=198
  _globals['_CONVERSATIONRESPONSE']._serialized_start=200
  _globals['_CONVERSATIONRESPONSE']._serialized_end=298
  _globals['_RESETREQUEST']._serialized_start=300
  _globals['_RESETREQUEST']._serialized_end=314
  _globals['_RESETRESPONSE']._serialized_start=316
  _globals['_RESETRESPONSE']._serialized_end=347
  _globals['_TRANSLATEREQUEST']._serialized_start=349
  _globals['_TRANSLATEREQUEST']._serialized_end=434
  _globals['_TRANSLATERESPONSE']._serialized_start=436
  _globals['_TRANSLATERESPONSE']._serialized_end=472
  _globals['_MEDCONNECTSERVICE']._serialized_start=475
  _globals['_MEDCONNECTSERVICE']._serialized_end=793
# @@protoc_insertion_point(module_scope)
