# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import medconnect_pb2 as medconnect__pb2


class MedConnectServiceStub(object):
    """MedConnect AI – multi-agent medical assistant (triage, history, SOAP, doctor matching)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
                '/medconnect.MedConnectService/HealthCheck',
                request_serializer=medconnect__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=medconnect__pb2.HealthCheckResponse.FromString,
                )
        self.Conversation = channel.unary_unary(
                '/medconnect.MedConnectService/Conversation',
                request_serializer=medconnect__pb2.ConversationRequest.SerializeToString,
                response_deserializer=medconnect__pb2.ConversationResponse.FromString,
                )
        self.Reset = channel.unary_unary(
                '/medconnect.MedConnectService/Reset',
                request_serializer=medconnect__pb2.ResetRequest.SerializeToString,
                response_deserializer=medconnect__pb2.ResetResponse.FromString,
                )
        self.Translate = channel.unary_unary(
                '/medconnect.MedConnectService/Translate',
                request_serializer=medconnect__pb2.TranslateRequest.SerializeToString,
                response_deserializer=medconnect__pb2.TranslateResponse.FromString,
                )


class MedConnectServiceServicer(object):
    """MedConnect AI – multi-agent medical assistant (triage, history, SOAP, doctor matching)
    """

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Conversation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Translate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MedConnectServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=medconnect__pb2.HealthCheckRequest.FromString,
                    response_serializer=medconnect__pb2.HealthCheckResponse.SerializeToString,
            ),
            'Conversation': grpc.unary_unary_rpc_method_handler(
                    servicer.Conversation,
                    request_deserializer=medconnect__pb2.ConversationRequest.FromString,
                    response_serializer=medconnect__pb2.ConversationResponse.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=medconnect__pb2.ResetRequest.FromString,
                    response_serializer=medconnect__pb2.ResetResponse.SerializeToString,
            ),
            'Translate': grpc.unary_unary_rpc_method_handler(
                    servicer.Translate,
                    request_deserializer=medconnect__pb2.TranslateRequest.FromString,
                    response_serializer=medconnect__pb2.TranslateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'medconnect.MedConnectService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MedConnectService(object):
    """MedConnect AI – multi-agent medical assistant (triage, history, SOAP, doctor matching)
    """

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/medconnect.MedConnectService/HealthCheck',
            medconnect__pb2.HealthCheckRequest.SerializeToString,
            medconnect__pb2.HealthCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Conversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/medconnect.MedConnectService/Conversation',
            medconnect__pb2.ConversationRequest.SerializeToString,
            medconnect__pb2.ConversationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/medconnect.MedConnectService/Reset',
            medconnect__pb2.ResetRequest.SerializeToString,
            medconnect__pb2.ResetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Translate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/medconnect.MedConnectService/Translate',
            medconnect__pb2.TranslateRequest.SerializeToString,
            medconnect__pb2.TranslateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
