// source: medconnect.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('medconnect_AJ_dev_outreach_test_1_medconnect.ConversationRequest', null, global);
goog.exportSymbol('medconnect_AJ_dev_outreach_test_1_medconnect.ConversationResponse', null, global);
goog.exportSymbol('medconnect_AJ_dev_outreach_test_1_medconnect.HealthCheckRequest', null, global);
goog.exportSymbol('medconnect_AJ_dev_outreach_test_1_medconnect.HealthCheckResponse', null, global);
goog.exportSymbol('medconnect_AJ_dev_outreach_test_1_medconnect.ResetRequest', null, global);
goog.exportSymbol('medconnect_AJ_dev_outreach_test_1_medconnect.ResetResponse', null, global);
goog.exportSymbol('medconnect_AJ_dev_outreach_test_1_medconnect.TranslateRequest', null, global);
goog.exportSymbol('medconnect_AJ_dev_outreach_test_1_medconnect.TranslateResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
medconnect_AJ_dev_outreach_test_1_medconnect.HealthCheckRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(medconnect_AJ_dev_outreach_test_1_medconnect.HealthCheckRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  medconnect_AJ_dev_outreach_test_1_medconnect.HealthCheckRequest.displayName = 'medconnect_AJ_dev_outreach_test_1_medconnect.HealthCheckRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
medconnect_AJ_dev_outreach_test_1_medconnect.HealthCheckResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(medconnect_AJ_dev_outreach_test_1_medconnect.HealthCheckResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  medconnect_AJ_dev_outreach_test_1_medconnect.HealthCheckResponse.displayName = 'medconnect_AJ_dev_outreach_test_1_medconnect.HealthCheckResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
medconnect_AJ_dev_outreach_test_1_medconnect.ConversationRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(medconnect_AJ_dev_outreach_test_1_medconnect.ConversationRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  medconnect_AJ_dev_outreach_test_1_medconnect.ConversationRequest.displayName = 'medconnect_AJ_dev_outreach_test_1_medconnect.ConversationRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
medconnect_AJ_dev_outreach_test_1_medconnect.ConversationResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(medconnect_AJ_dev_outreach_test_1_medconnect.ConversationResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  medconnect_AJ_dev_outreach_test_1_medconnect.ConversationResponse.displayName = 'medconnect_AJ_dev_outreach_test_1_medconnect.ConversationResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
medconnect_AJ_dev_outreach_test_1_medconnect.ResetRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(medconnect_AJ_dev_outreach_test_1_medconnect.ResetRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  medconnect_AJ_dev_outreach_test_1_medconnect.ResetRequest.displayName = 'medconnect_AJ_dev_outreach_test_1_medconnect.ResetRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
medconnect_AJ_dev_outreach_test_1_medconnect.ResetResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(medconnect_AJ_dev_outreach_test_1_medconnect.ResetResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  medconnect_AJ_dev_outreach_test_1_medconnect.ResetResponse.displayName = 'medconnect_AJ_dev_outreach_test_1_medconnect.ResetResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
medconnect_AJ_dev_outreach_test_1_medconnect.TranslateRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(medconnect_AJ_dev_outreach_test_1_medconnect.TranslateRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  medconnect_AJ_dev_outreach_test_1_medconnect.TranslateRequest.displayName = 'medconnect_AJ_dev_outreach_test_1_medconnect.TranslateRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
medconnect_AJ_dev_outreach_test_1_medconnect.TranslateResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(medconnect_AJ_dev_outreach_test_1_medconnect.TranslateResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  medconnect_AJ_dev_outreach_test_1_medconnect.TranslateResponse.displayName = 'medconnect_AJ_dev_outreach_test_1_medconnect.TranslateResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
medconnect_AJ_dev_outreach_test_1_medconnect.HealthCheckRequest.prototype.toObject = function(opt_includeInstance) {
  return medconnect_AJ_dev_outreach_test_1_medconnect.HealthCheckRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!medconnect_AJ_dev_outreach_test_1_medconnect.HealthCheckRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
medconnect_AJ_dev_outreach_test_1_medconnect.HealthCheckRequest.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!medconnect_AJ_dev_outreach_test_1_medconnect.HealthCheckRequest}
 */
medconnect_AJ_dev_outreach_test_1_medconnect.HealthCheckRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new medconnect_AJ_dev_outreach_test_1_medconnect.HealthCheckRequest;
  return medconnect_AJ_dev_outreach_test_1_medconnect.HealthCheckRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!medconnect_AJ_dev_outreach_test_1_medconnect.HealthCheckRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!medconnect_AJ_dev_outreach_test_1_medconnect.HealthCheckRequest}
 */
medconnect_AJ_dev_outreach_test_1_medconnect.HealthCheckRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
medconnect_AJ_dev_outreach_test_1_medconnect.HealthCheckRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  medconnect_AJ_dev_outreach_test_1_medconnect.HealthCheckRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!medconnect_AJ_dev_outreach_test_1_medconnect.HealthCheckRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
medconnect_AJ_dev_outreach_test_1_medconnect.HealthCheckRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
medconnect_AJ_dev_outreach_test_1_medconnect.HealthCheckResponse.prototype.toObject = function(opt_includeInstance) {
  return medconnect_AJ_dev_outreach_test_1_medconnect.HealthCheckResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!medconnect_AJ_dev_outreach_test_1_medconnect.HealthCheckResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
medconnect_AJ_dev_outreach_test_1_medconnect.HealthCheckResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
status: jspb.Message.getFieldWithDefault(msg, 1, ""),
message: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!medconnect_AJ_dev_outreach_test_1_medconnect.HealthCheckResponse}
 */
medconnect_AJ_dev_outreach_test_1_medconnect.HealthCheckResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new medconnect_AJ_dev_outreach_test_1_medconnect.HealthCheckResponse;
  return medconnect_AJ_dev_outreach_test_1_medconnect.HealthCheckResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!medconnect_AJ_dev_outreach_test_1_medconnect.HealthCheckResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!medconnect_AJ_dev_outreach_test_1_medconnect.HealthCheckResponse}
 */
medconnect_AJ_dev_outreach_test_1_medconnect.HealthCheckResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setStatus(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
medconnect_AJ_dev_outreach_test_1_medconnect.HealthCheckResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  medconnect_AJ_dev_outreach_test_1_medconnect.HealthCheckResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!medconnect_AJ_dev_outreach_test_1_medconnect.HealthCheckResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
medconnect_AJ_dev_outreach_test_1_medconnect.HealthCheckResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStatus();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string status = 1;
 * @return {string}
 */
medconnect_AJ_dev_outreach_test_1_medconnect.HealthCheckResponse.prototype.getStatus = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!medconnect_AJ_dev_outreach_test_1_medconnect.HealthCheckResponse} returns this
 */
medconnect_AJ_dev_outreach_test_1_medconnect.HealthCheckResponse.prototype.setStatus = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string message = 2;
 * @return {string}
 */
medconnect_AJ_dev_outreach_test_1_medconnect.HealthCheckResponse.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!medconnect_AJ_dev_outreach_test_1_medconnect.HealthCheckResponse} returns this
 */
medconnect_AJ_dev_outreach_test_1_medconnect.HealthCheckResponse.prototype.setMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
medconnect_AJ_dev_outreach_test_1_medconnect.ConversationRequest.prototype.toObject = function(opt_includeInstance) {
  return medconnect_AJ_dev_outreach_test_1_medconnect.ConversationRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!medconnect_AJ_dev_outreach_test_1_medconnect.ConversationRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
medconnect_AJ_dev_outreach_test_1_medconnect.ConversationRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
message: jspb.Message.getFieldWithDefault(msg, 1, ""),
audio: jspb.Message.getFieldWithDefault(msg, 2, ""),
premium: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
language: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!medconnect_AJ_dev_outreach_test_1_medconnect.ConversationRequest}
 */
medconnect_AJ_dev_outreach_test_1_medconnect.ConversationRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new medconnect_AJ_dev_outreach_test_1_medconnect.ConversationRequest;
  return medconnect_AJ_dev_outreach_test_1_medconnect.ConversationRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!medconnect_AJ_dev_outreach_test_1_medconnect.ConversationRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!medconnect_AJ_dev_outreach_test_1_medconnect.ConversationRequest}
 */
medconnect_AJ_dev_outreach_test_1_medconnect.ConversationRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setAudio(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setPremium(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setLanguage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
medconnect_AJ_dev_outreach_test_1_medconnect.ConversationRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  medconnect_AJ_dev_outreach_test_1_medconnect.ConversationRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!medconnect_AJ_dev_outreach_test_1_medconnect.ConversationRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
medconnect_AJ_dev_outreach_test_1_medconnect.ConversationRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAudio();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPremium();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getLanguage();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional string message = 1;
 * @return {string}
 */
medconnect_AJ_dev_outreach_test_1_medconnect.ConversationRequest.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!medconnect_AJ_dev_outreach_test_1_medconnect.ConversationRequest} returns this
 */
medconnect_AJ_dev_outreach_test_1_medconnect.ConversationRequest.prototype.setMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string audio = 2;
 * @return {string}
 */
medconnect_AJ_dev_outreach_test_1_medconnect.ConversationRequest.prototype.getAudio = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!medconnect_AJ_dev_outreach_test_1_medconnect.ConversationRequest} returns this
 */
medconnect_AJ_dev_outreach_test_1_medconnect.ConversationRequest.prototype.setAudio = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional bool premium = 3;
 * @return {boolean}
 */
medconnect_AJ_dev_outreach_test_1_medconnect.ConversationRequest.prototype.getPremium = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!medconnect_AJ_dev_outreach_test_1_medconnect.ConversationRequest} returns this
 */
medconnect_AJ_dev_outreach_test_1_medconnect.ConversationRequest.prototype.setPremium = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional string language = 4;
 * @return {string}
 */
medconnect_AJ_dev_outreach_test_1_medconnect.ConversationRequest.prototype.getLanguage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!medconnect_AJ_dev_outreach_test_1_medconnect.ConversationRequest} returns this
 */
medconnect_AJ_dev_outreach_test_1_medconnect.ConversationRequest.prototype.setLanguage = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
medconnect_AJ_dev_outreach_test_1_medconnect.ConversationResponse.prototype.toObject = function(opt_includeInstance) {
  return medconnect_AJ_dev_outreach_test_1_medconnect.ConversationResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!medconnect_AJ_dev_outreach_test_1_medconnect.ConversationResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
medconnect_AJ_dev_outreach_test_1_medconnect.ConversationResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
message: jspb.Message.getFieldWithDefault(msg, 1, ""),
audio: jspb.Message.getFieldWithDefault(msg, 2, ""),
doctorId: jspb.Message.getFieldWithDefault(msg, 3, ""),
medicalSummary: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!medconnect_AJ_dev_outreach_test_1_medconnect.ConversationResponse}
 */
medconnect_AJ_dev_outreach_test_1_medconnect.ConversationResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new medconnect_AJ_dev_outreach_test_1_medconnect.ConversationResponse;
  return medconnect_AJ_dev_outreach_test_1_medconnect.ConversationResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!medconnect_AJ_dev_outreach_test_1_medconnect.ConversationResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!medconnect_AJ_dev_outreach_test_1_medconnect.ConversationResponse}
 */
medconnect_AJ_dev_outreach_test_1_medconnect.ConversationResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setAudio(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDoctorId(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setMedicalSummary(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
medconnect_AJ_dev_outreach_test_1_medconnect.ConversationResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  medconnect_AJ_dev_outreach_test_1_medconnect.ConversationResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!medconnect_AJ_dev_outreach_test_1_medconnect.ConversationResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
medconnect_AJ_dev_outreach_test_1_medconnect.ConversationResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAudio();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDoctorId();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getMedicalSummary();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional string message = 1;
 * @return {string}
 */
medconnect_AJ_dev_outreach_test_1_medconnect.ConversationResponse.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!medconnect_AJ_dev_outreach_test_1_medconnect.ConversationResponse} returns this
 */
medconnect_AJ_dev_outreach_test_1_medconnect.ConversationResponse.prototype.setMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string audio = 2;
 * @return {string}
 */
medconnect_AJ_dev_outreach_test_1_medconnect.ConversationResponse.prototype.getAudio = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!medconnect_AJ_dev_outreach_test_1_medconnect.ConversationResponse} returns this
 */
medconnect_AJ_dev_outreach_test_1_medconnect.ConversationResponse.prototype.setAudio = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string doctor_id = 3;
 * @return {string}
 */
medconnect_AJ_dev_outreach_test_1_medconnect.ConversationResponse.prototype.getDoctorId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!medconnect_AJ_dev_outreach_test_1_medconnect.ConversationResponse} returns this
 */
medconnect_AJ_dev_outreach_test_1_medconnect.ConversationResponse.prototype.setDoctorId = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string medical_summary = 4;
 * @return {string}
 */
medconnect_AJ_dev_outreach_test_1_medconnect.ConversationResponse.prototype.getMedicalSummary = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!medconnect_AJ_dev_outreach_test_1_medconnect.ConversationResponse} returns this
 */
medconnect_AJ_dev_outreach_test_1_medconnect.ConversationResponse.prototype.setMedicalSummary = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
medconnect_AJ_dev_outreach_test_1_medconnect.ResetRequest.prototype.toObject = function(opt_includeInstance) {
  return medconnect_AJ_dev_outreach_test_1_medconnect.ResetRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!medconnect_AJ_dev_outreach_test_1_medconnect.ResetRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
medconnect_AJ_dev_outreach_test_1_medconnect.ResetRequest.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!medconnect_AJ_dev_outreach_test_1_medconnect.ResetRequest}
 */
medconnect_AJ_dev_outreach_test_1_medconnect.ResetRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new medconnect_AJ_dev_outreach_test_1_medconnect.ResetRequest;
  return medconnect_AJ_dev_outreach_test_1_medconnect.ResetRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!medconnect_AJ_dev_outreach_test_1_medconnect.ResetRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!medconnect_AJ_dev_outreach_test_1_medconnect.ResetRequest}
 */
medconnect_AJ_dev_outreach_test_1_medconnect.ResetRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
medconnect_AJ_dev_outreach_test_1_medconnect.ResetRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  medconnect_AJ_dev_outreach_test_1_medconnect.ResetRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!medconnect_AJ_dev_outreach_test_1_medconnect.ResetRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
medconnect_AJ_dev_outreach_test_1_medconnect.ResetRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
medconnect_AJ_dev_outreach_test_1_medconnect.ResetResponse.prototype.toObject = function(opt_includeInstance) {
  return medconnect_AJ_dev_outreach_test_1_medconnect.ResetResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!medconnect_AJ_dev_outreach_test_1_medconnect.ResetResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
medconnect_AJ_dev_outreach_test_1_medconnect.ResetResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
status: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!medconnect_AJ_dev_outreach_test_1_medconnect.ResetResponse}
 */
medconnect_AJ_dev_outreach_test_1_medconnect.ResetResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new medconnect_AJ_dev_outreach_test_1_medconnect.ResetResponse;
  return medconnect_AJ_dev_outreach_test_1_medconnect.ResetResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!medconnect_AJ_dev_outreach_test_1_medconnect.ResetResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!medconnect_AJ_dev_outreach_test_1_medconnect.ResetResponse}
 */
medconnect_AJ_dev_outreach_test_1_medconnect.ResetResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setStatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
medconnect_AJ_dev_outreach_test_1_medconnect.ResetResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  medconnect_AJ_dev_outreach_test_1_medconnect.ResetResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!medconnect_AJ_dev_outreach_test_1_medconnect.ResetResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
medconnect_AJ_dev_outreach_test_1_medconnect.ResetResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStatus();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string status = 1;
 * @return {string}
 */
medconnect_AJ_dev_outreach_test_1_medconnect.ResetResponse.prototype.getStatus = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!medconnect_AJ_dev_outreach_test_1_medconnect.ResetResponse} returns this
 */
medconnect_AJ_dev_outreach_test_1_medconnect.ResetResponse.prototype.setStatus = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
medconnect_AJ_dev_outreach_test_1_medconnect.TranslateRequest.prototype.toObject = function(opt_includeInstance) {
  return medconnect_AJ_dev_outreach_test_1_medconnect.TranslateRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!medconnect_AJ_dev_outreach_test_1_medconnect.TranslateRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
medconnect_AJ_dev_outreach_test_1_medconnect.TranslateRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
message: jspb.Message.getFieldWithDefault(msg, 1, ""),
sourceLanguage: jspb.Message.getFieldWithDefault(msg, 2, ""),
targetLanguage: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!medconnect_AJ_dev_outreach_test_1_medconnect.TranslateRequest}
 */
medconnect_AJ_dev_outreach_test_1_medconnect.TranslateRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new medconnect_AJ_dev_outreach_test_1_medconnect.TranslateRequest;
  return medconnect_AJ_dev_outreach_test_1_medconnect.TranslateRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!medconnect_AJ_dev_outreach_test_1_medconnect.TranslateRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!medconnect_AJ_dev_outreach_test_1_medconnect.TranslateRequest}
 */
medconnect_AJ_dev_outreach_test_1_medconnect.TranslateRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSourceLanguage(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setTargetLanguage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
medconnect_AJ_dev_outreach_test_1_medconnect.TranslateRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  medconnect_AJ_dev_outreach_test_1_medconnect.TranslateRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!medconnect_AJ_dev_outreach_test_1_medconnect.TranslateRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
medconnect_AJ_dev_outreach_test_1_medconnect.TranslateRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getSourceLanguage();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTargetLanguage();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string message = 1;
 * @return {string}
 */
medconnect_AJ_dev_outreach_test_1_medconnect.TranslateRequest.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!medconnect_AJ_dev_outreach_test_1_medconnect.TranslateRequest} returns this
 */
medconnect_AJ_dev_outreach_test_1_medconnect.TranslateRequest.prototype.setMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string source_language = 2;
 * @return {string}
 */
medconnect_AJ_dev_outreach_test_1_medconnect.TranslateRequest.prototype.getSourceLanguage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!medconnect_AJ_dev_outreach_test_1_medconnect.TranslateRequest} returns this
 */
medconnect_AJ_dev_outreach_test_1_medconnect.TranslateRequest.prototype.setSourceLanguage = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string target_language = 3;
 * @return {string}
 */
medconnect_AJ_dev_outreach_test_1_medconnect.TranslateRequest.prototype.getTargetLanguage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!medconnect_AJ_dev_outreach_test_1_medconnect.TranslateRequest} returns this
 */
medconnect_AJ_dev_outreach_test_1_medconnect.TranslateRequest.prototype.setTargetLanguage = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
medconnect_AJ_dev_outreach_test_1_medconnect.TranslateResponse.prototype.toObject = function(opt_includeInstance) {
  return medconnect_AJ_dev_outreach_test_1_medconnect.TranslateResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!medconnect_AJ_dev_outreach_test_1_medconnect.TranslateResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
medconnect_AJ_dev_outreach_test_1_medconnect.TranslateResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
message: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!medconnect_AJ_dev_outreach_test_1_medconnect.TranslateResponse}
 */
medconnect_AJ_dev_outreach_test_1_medconnect.TranslateResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new medconnect_AJ_dev_outreach_test_1_medconnect.TranslateResponse;
  return medconnect_AJ_dev_outreach_test_1_medconnect.TranslateResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!medconnect_AJ_dev_outreach_test_1_medconnect.TranslateResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!medconnect_AJ_dev_outreach_test_1_medconnect.TranslateResponse}
 */
medconnect_AJ_dev_outreach_test_1_medconnect.TranslateResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
medconnect_AJ_dev_outreach_test_1_medconnect.TranslateResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  medconnect_AJ_dev_outreach_test_1_medconnect.TranslateResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!medconnect_AJ_dev_outreach_test_1_medconnect.TranslateResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
medconnect_AJ_dev_outreach_test_1_medconnect.TranslateResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string message = 1;
 * @return {string}
 */
medconnect_AJ_dev_outreach_test_1_medconnect.TranslateResponse.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!medconnect_AJ_dev_outreach_test_1_medconnect.TranslateResponse} returns this
 */
medconnect_AJ_dev_outreach_test_1_medconnect.TranslateResponse.prototype.setMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


goog.object.extend(exports, medconnect_AJ_dev_outreach_test_1_medconnect);
